spring:
  application:
    name: ribbon

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.99.100:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5

ribbon:
  NFLoadBalancerPingInterval: 3
 
helloworld-service:
  ribbon:
    eureka:
      enabled: true
      ServerListRefreshInterval: 1000
 
server:
  port: 8888
    
---
spring:
  profiles: docker
  application:
    name: ribbon

eureka:
  instance:
    hostname: ribbon
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
      
helloworld-service:
  ribbon:
    eureka:
      enabled: true
      ServerListRefreshInterval: 1000
 
server:
  port: 8888